name: bonklang
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  antlr4: 4.13.0
#   path: ^1.8.0
  dart_dot:
    git: https://github.com/kevinpthorne/dart-graphviz-dot.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
